BookStoreProject/Models/Libro.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;
namespace BookStoreProject.Models
{
    public class Libro
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        
        [Required(ErrorMessage ="*Campo requerido")]
        [MaxLength(40, ErrorMessage ="*Longitud maxima {1}")]
        public string Titulo { get; set; }
        
        [Required(ErrorMessage = "*Campo requerido")]
        [MaxLength(40, ErrorMessage = "*Longitud maxima {1}")]
        [RegularExpression(@"[a-zA-z ]{3,}", ErrorMessage = "*Campo con números")]
        public string Autor { get; set; }
        
        [Required(ErrorMessage = "*Campo requerido")]
        [MaxLength(40, ErrorMessage = "*Longitud maxima {1}")]
        [RegularExpression(@"[a-zA-z ]{3,}", ErrorMessage = "*Campo con números")]
        public string Editorial { get; set; }
       
        [Required(ErrorMessage = "*Campo requerido")]
        [MaxLength(40, ErrorMessage = "*Longitud maxima {1}")]
        [RegularExpression(@"[a-zA-z ]{3,}", ErrorMessage = "*Campo con números")]
        public string Genero { get; set; }
       
        [Required(ErrorMessage = "*Campo requerido")]
        [Range(1,1000000, ErrorMessage = "*Precio menor a 1")]
        public int Precio { get; set; }

    }
}

BookStoreProject/Controllers/ComentarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BookStoreProject.Context;
using BookStoreProject.Models;
using Microsoft.AspNetCore.Authorization;

namespace BookStoreProject.Controllers
{
    [Authorize]
    public class ComentarioController : Controller
    {
        private readonly BookStoreDBContext _context;

        public ComentarioController(BookStoreDBContext context)
        {
            _context = context;
        }

        // GET: Comentario/Delete/5
        [Authorize(Roles = nameof(Rol.Administrador))]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comentario = await _context.Comentarios
                .Include(c => c.Libro)
                .Include(c => c.Usuario)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (comentario == null)
            {
                return NotFound();
            }

            return View(comentario);
        }

        // POST: Comentario/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = nameof(Rol.Administrador))]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var comentario = await _context.Comentarios.FindAsync(id);
            _context.Comentarios.Remove(comentario);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", "Libro");
        }

        [Authorize(Roles = nameof(Rol.Administrador))]
        private bool ComentarioExists(int id)
        {
            return _context.Comentarios.Any(e => e.Id == id);
        }
    }
}

BookStoreProject/Controllers/LibroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BookStoreProject.Context;
using BookStoreProject.Models;
using Microsoft.AspNetCore.Authorization;

namespace BookStoreProject.Controllers
{
    [Authorize]
    public class LibroController : Controller
    {
        private readonly BookStoreDBContext _context;

        public LibroController(BookStoreDBContext context)
        {
            _context = context;
        }

        //Buscador
        public ActionResult Index(string cadenaBuscada)
        {

            var libros = from l in _context.Libros
                         select l;

            if (!String.IsNullOrEmpty(cadenaBuscada))
            {
                libros = libros.Where(s => s.Titulo.Contains(cadenaBuscada));
            }

            return View(libros);
        }


        // GET: Libro/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var libro = await _context.Libros
                .FirstOrDefaultAsync(m => m.Id == id);
            if (libro == null)
            {
                return NotFound();
            }

            var comentarios = _context.Comentarios.Include(c => c.Libro).Include(c => c.Usuario).Where(c => c.LibroId == id);
            ViewData["Comments"] = comentarios;

            return View(libro);
        }
       
        // GET: Libro/Create
        [Authorize(Roles = nameof(Rol.Administrador))]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Libro/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = nameof(Rol.Administrador))]
        public async Task<IActionResult> Create([Bind("Id,Titulo,Autor,Editorial,Genero,Precio")] Libro libro)
        {
            if (ModelState.IsValid)
            {
                _context.Add(libro);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(libro);
        }

        // GET: Libro/Edit/5
        [Authorize(Roles = nameof(Rol.Administrador))]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var libro = await _context.Libros.FindAsync(id);
            if (libro == null)
            {
                return NotFound();
            }

            return View(libro);
        }

        // POST: Libro/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = nameof(Rol.Administrador))]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Titulo,Autor,Editorial,Genero,Precio")] Libro libro)
        {
            if (id != libro.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(libro);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LibroExists(libro.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(libro);
        }

        // GET: Libro/Delete/5
        [Authorize(Roles = nameof(Rol.Administrador))]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var libro = await _context.Libros
                .FirstOrDefaultAsync(m => m.Id == id);
            if (libro == null)
            {
                return NotFound();
            }

            return View(libro);
        }

        // POST: Libro/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = nameof(Rol.Administrador))]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var libro = await _context.Libros.FindAsync(id);
            _context.Libros.Remove(libro);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = nameof(Rol.Administrador))]
        private bool LibroExists(int id)
        {
            return _context.Libros.Any(e => e.Id == id);
        }


        public ActionResult Comentar(int Id, string Comment)
        {
            if (Comment != null)
            {
                var nuevoComentario = new Comentario();
                nuevoComentario.Comment = Comment;
                nuevoComentario.LibroId = Id;
                var libro = _context.Libros.Find(Id);
                nuevoComentario.Libro = libro;
                var userName = User.Identity.Name;
                var user = _context.Usuarios.FirstOrDefault(u => u.User == userName);
                nuevoComentario.Usuario = user;
                nuevoComentario.UsuarioId = user.Id;
                nuevoComentario.Fecha = DateTime.Now;
                _context.Comentarios.Add(nuevoComentario);
                _context.SaveChanges();

            }
            return RedirectToAction("Index", "Libro");
        }
        

        }
    }


   

BookStoreProject/Controllers/VentaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BookStoreProject.Context;
using BookStoreProject.Models;
using Microsoft.AspNetCore.Authorization;

namespace BookStoreProject.Controllers
{
    [Authorize]
    public class VentaController : Controller
    {
        private readonly BookStoreDBContext _context;

        public VentaController(BookStoreDBContext context)
        {
            _context = context;
        }
        
        // GET: Venta
        [Authorize(Roles = nameof(Rol.Administrador))]
        public ActionResult Index(string cadenaBuscada)
        {

            var ventas = from v in _context.Ventas.Include(v => v.Libro)
                             select v;

            if (!String.IsNullOrEmpty(cadenaBuscada))
            {
                ventas = ventas.Where(v => v.Libro.Titulo.Contains(cadenaBuscada));
            }

            ViewBag.TotalVentas = ventas.Count();
            ViewBag.TotalVendido = ventas.Select(v => v.Libro.Precio).Sum();
            return View(ventas);
        }

     

        // GET: Venta/Details/5
        [Authorize(Roles = nameof(Rol.Administrador))]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var venta = await _context.Ventas
               .Include(v => v.Libro)
               .FirstOrDefaultAsync(m => m.Id == id);

            if (venta == null)
            {
                return NotFound();
            }

            return View(venta);
        }

        // GET: Venta/Create
        [Authorize(Roles = nameof(Rol.Administrador))]
        public IActionResult Create()
        {
            ViewData["LibroId"] = new SelectList(_context.Libros, "Id", "Autor");
            return View();
        }

        // POST: Venta/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = nameof(Rol.Administrador))]
        public async Task<IActionResult> Create([Bind("Id,Nombre,Apellido,Dni,Calle,Altura,Provincia,Tarjeta,NumeroTarjeta,LibroId")] Venta venta)
        {
            if (ModelState.IsValid)
            {
                _context.Add(venta);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["LibroId"] = new SelectList(_context.Libros, "Id", "Autor", venta.LibroId);
            return View(venta);
        }

        // GET: Venta/Delete/5
        [Authorize(Roles = nameof(Rol.Administrador))]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var venta = await _context.Ventas
                .Include(v => v.Libro)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (venta == null)
            {
                return NotFound();
            }

            return View(venta);
        }

        // POST: Venta/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = nameof(Rol.Administrador))]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var venta = await _context.Ventas.FindAsync(id);
            _context.Ventas.Remove(venta);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = nameof(Rol.Administrador))]
        private bool VentaExists(int id)
        {
            return _context.Ventas.Any(e => e.Id == id);
        }


        public ActionResult Comprar()
        {
            return View();
        }

        
        [HttpPost]
        public ActionResult Comprar(int Id, string Nombre, string Apellido, int Dni, string Calle, int Altura,
            string Provincia, int Telefono, string Email, string Tarjeta, long NumeroTarjeta)
        {
            var venta = new Venta();
            venta.Nombre = Nombre;
            venta.Apellido = Apellido;
            venta.Dni = Dni;
            venta.Calle = Calle;
            venta.Altura = Altura;
            venta.Provincia = Provincia;
            venta.Telefono = Telefono;
            venta.Email = Email;
            venta.Tarjeta = Tarjeta;
            venta.NumeroTarjeta = NumeroTarjeta;
            venta.LibroId = Id;
            var libro = _context.Libros.Find(Id);
            venta.Libro = libro;
            venta.Fecha = DateTime.Now;
            if (ModelState.IsValid)
            {
                _context.Ventas.Add(venta);
            _context.SaveChanges();
                ViewBag.LibroId = venta.LibroId;
                return View("CompraExitosa");

            }
            
            return RedirectToAction("Index", "Home");
        }
        
    }
}

BookStoreProject/Views/Libro/Create.cshtml
@model BookStoreProject.Models.Libro

@{
    ViewData["Title"] = "Create";
}

<div class="btnVolver">
    <a class="btnAbm" asp-action="Index">Volver </a>
</div>

<h2 class="tituloCrear">Agregar nuevo libro</h2>



<div>
    <div class="create">
        <!--class="col-md-4">-->
        <form id="formCreate" asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control"/>
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Autor" class="control-label"></label>
                <input asp-for="Autor" class="form-control" />
                <span asp-validation-for="Autor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Editorial" class="control-label"></label>
                <input asp-for="Editorial" class="form-control" />
                <span asp-validation-for="Editorial" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genero" class="control-label"></label>
                <input asp-for="Genero" class="form-control" />
                <span asp-validation-for="Genero" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Precio" class="control-label"></label>
                <input asp-for="Precio" class="form-control" />
                <span asp-validation-for="Precio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input class="btnCreate" type="submit" value="Agregar" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BookStoreProject/Views/Libro/Delete.cshtml
@model BookStoreProject.Models.Libro

@{
    ViewData["Title"] = "Delete";
}

<div class="btnVolver">
    <a class="btnAbm" asp-action="Index">Volver</a>
</div>

<h3 class="tituloEliminar">¿Está seguro que quiere eliminar este libro?</h3>

<div class="eliminar">
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titulo):
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Autor):
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Autor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Editorial):
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Editorial)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genero):
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genero)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Precio):
        </dt>
        <dd class = "col-sm-10">
            $@Html.DisplayFor(model => model.Precio)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Eliminar" class="btnCreate" />
    </form>
</div>

BookStoreProject/Views/Libro/Details.cshtml
@model BookStoreProject.Models.Libro

@{
    ViewData["Title"] = "Details";
}

@if (User.IsInRole(nameof(Rol.Administrador)))
{
    <div class="btnVolver">
        <a class="btnAbm" asp-action="Edit" asp-route-id="@Model.Id">Editar</a>
    </div>

}

@{
    var cargarImagen = "http://localhost:52620/imagenes/" + @Model.Id + ".jpg";

}
<img class="libro" src=@cargarImagen alt="Model.Titulo" />

<div class="detalle">
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Autor)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Autor)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Editorial)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Editorial)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Genero)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Genero)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Precio)
        </dt>
        <dd class="col-sm-10">
            $@Html.DisplayFor(model => model.Precio)
        </dd>
    </dl>
</div>

<form asp-action="Comentar" asp-route-id="@Model.Id" method="post">
    <textarea id="campoComentario" name="Comment" rows="3" cols="100" placeholder="Escriba un comentario..."></textarea><br />
    <input id="btnComentar" type="submit" name="Comentar" value="Comentar" />
</form>
<div>
    <a class="btnCompra" asp-controller="Venta" asp-action="Comprar" asp-route-id="@Model.Id">Comprar</a><br />
</div>

<h3>Comentarios</h3>
<table class="table">
    <tbody>
        @foreach (var comentario in ViewData["Comments"] as IQueryable<Comentario>)
        {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => comentario.Fecha)
        </td>
        <td>
            @Html.DisplayFor(modelItem => comentario.Comment)
        </td>
        <td>
            @Html.DisplayFor(modelItem => comentario.Usuario.Nombre)
        </td>

        <td class="dropdown">
            @if (User.IsInRole(nameof(Rol.Administrador)))
            {
                <button class="dropbtn">Opciones</button>
                <div class="dropdown-content">
                    <a class="btnAbm" asp-controller="Comentario" asp-action="Delete" asp-route-id="@comentario.Id">Eliminar</a>
                </div>
            }
        </td>


    </tr>
        }
    </tbody>
</table>

BookStoreProject/Views/Libro/Edit.cshtml
@model BookStoreProject.Models.Libro

@{
    ViewData["Title"] = "Edit";
}

<div class="btnVolver">
    <a class="btnAbm" asp-action="Index">Volver a la lista de libros</a>
</div>

<h2 class="tituloEdite">Editar</h2>

<div class="row">
    <div class="create">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Autor" class="control-label"></label>
                <input asp-for="Autor" class="form-control" />
                <span asp-validation-for="Autor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Editorial" class="control-label"></label>
                <input asp-for="Editorial" class="form-control" />
                <span asp-validation-for="Editorial" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genero" class="control-label"></label>
                <input asp-for="Genero" class="form-control" />
                <span asp-validation-for="Genero" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Precio" class="control-label"></label>
                <input asp-for="Precio" class="form-control" />
                <span asp-validation-for="Precio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btnCreate" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BookStoreProject/Views/Libro/Index.cshtml
@model IEnumerable<BookStoreProject.Models.Libro>;

@{
    ViewData["Title"] = "Index";
}

<p class="btnAgregar">
    @if (User.IsInRole(nameof(Rol.Administrador)))
    {
        <a class="btnAbm" asp-action="Create">Agregar nuevo libro</a>
    }

    <!--***************************************************-->

<div class="formBuscador">
    @using (Html.BeginForm())
    {
        <p>
            <input class="buscador" id="cadenaBuscada" name="cadenaBuscada" type="text" value="" placeholder="Titulo del libro..." />
            <input class="buscar" type="submit" value="Buscar" />
        </p>
        @if (Model.Count() < 1)
        {
            <p class="notFound">¡Lo sentimos, no se ha encontrado ningún libro!</p>
        }
        else
        {
            <p>Resultados: @Model.Count()</p>
        }
    }
</div>

    <!--***************************************************-->


    <table class="table">
        <thead>
            <tr class="columna">
                <th>
                    @Html.DisplayNameFor(model => model.Titulo)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Autor)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Precio)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Titulo)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Autor)
                    </td>
                    <td>
                        $ @Html.DisplayFor(modelItem => item.Precio)
                    </td>
                    <td class="dropdown">
                        @if (User.IsInRole(nameof(Rol.Administrador)))
                        {
                            <button class="dropbtn">Opciones</button>
                            <div class="dropdown-content">
                                <a class="btnAbm" asp-action="Edit" asp-route-id="@item.Id">Editar</a>
                                <a class="btnAbm" asp-action="Details" asp-route-id="@item.Id">Ver detalles</a>
                                <a class="btnAbm" asp-action="Delete" asp-route-id="@item.Id">Eliminar</a>
                            </div>
                        }
                        else
                        {
                            <button class="dropbtn">Opciones</button>
                            <div class="dropdown-content">
                                <a class="btnAbm" asp-action="Details" asp-route-id="@item.Id">Ver detalles</a>
                            </div>

                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>