BookStoreProject/Controllers/SucursalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BookStoreProject.Context;
using BookStoreProject.Models;
using Microsoft.AspNetCore.Authorization;

namespace BookStoreProject.Controllers
 {
    [Authorize]
    public class SucursalController : Controller
    {
        private readonly BookStoreDBContext _context;

        public SucursalController(BookStoreDBContext context)
        {
            _context = context;
        }


        public ActionResult Index(string cadenaBuscada)
        {

            var sucursales = from s in _context.Sucursal
                         select s;

            if (!String.IsNullOrEmpty(cadenaBuscada))
            {
                sucursales = sucursales.Where(s => s.Direccion.Contains(cadenaBuscada));
            }

            return View(sucursales);
        }

        // GET: Sucursal/Create
        [Authorize(Roles = nameof(Rol.Administrador))]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Sucursal/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = nameof(Rol.Administrador))]
        public async Task<IActionResult> Create([Bind("Id,Nombre,Direccion,Telefono,Email,HoraApertura,HoraCierre")] Sucursal sucursal)
        {
            if (ModelState.IsValid)
            {
                _context.Add(sucursal);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(sucursal);
        }

        // GET: Sucursal/Edit/5
        [Authorize(Roles = nameof(Rol.Administrador))]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sucursal = await _context.Sucursal.FindAsync(id);
            if (sucursal == null)
            {
                return NotFound();
            }
            return View(sucursal);
        }

        // POST: Sucursal/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = nameof(Rol.Administrador))]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nombre,Direccion,Telefono,Email,HoraApertura,HoraCierre")] Sucursal sucursal)
        {
            if (id != sucursal.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(sucursal);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SucursalExists(sucursal.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(sucursal);
        }

        // GET: Sucursal/Delete/5
        [Authorize(Roles = nameof(Rol.Administrador))]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sucursal = await _context.Sucursal
                .FirstOrDefaultAsync(m => m.Id == id);
            if (sucursal == null)
            {
                return NotFound();
            }

            return View(sucursal);
        }

        // POST: Sucursal/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = nameof(Rol.Administrador))]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var sucursal = await _context.Sucursal.FindAsync(id);
            _context.Sucursal.Remove(sucursal);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = nameof(Rol.Administrador))]
        private bool SucursalExists(int id)
        {
            return _context.Sucursal.Any(e => e.Id == id);
        }
    }
}

BookStoreProject/Controllers/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BookStoreProject.Context;
using BookStoreProject.Models;

namespace BookStoreProject.Controllers
{

        [AllowAnonymous]
        public class UsuarioController : Controller
        {
            private readonly BookStoreDBContext _context;
            private readonly ISeguridad seguridad = new SeguridadBasica();

            public UsuarioController(BookStoreDBContext context)
            {
                _context = context;
            }

            // GET: Usuarios
            public IActionResult Ingresar(string returnUrl)
            {
                TempData["UrlIngreso"] = returnUrl;
                return View();
            }

        [HttpPost]
        public async Task<IActionResult> Ingresar(string usuario, string pass)
        {
            // Guardamos la URL a la que debemos redirigir al usuario
            var urlIngreso = TempData["UrlIngreso"] as string;

            // Verificamos que ambos esten informados
            if (!string.IsNullOrEmpty(usuario) && !string.IsNullOrEmpty(pass))
            {

                // Verificamos que exista el usuario
                var user = await _context.Usuarios.FirstOrDefaultAsync(u => u.User == usuario);
                if (user != null)
                {

                    // Verificamos que coincida la contraseña
                    var contraseña = seguridad.EncriptarPass(pass);
                    if (contraseña.SequenceEqual(user.Contraseña))
                    {

                        // Creamos los Claims (credencial de acceso con informacion del usuario)
                        ClaimsIdentity identidad = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);

                        // Agregamos a la credencial el nombre de usuario
                        identidad.AddClaim(new Claim(ClaimTypes.Name, usuario));
                        // Agregamos a la credencial el nombre del usuarioComun/administrador
                        identidad.AddClaim(new Claim(ClaimTypes.GivenName, user.Nombre));
                        // Agregamos a la credencial el Rol
                        identidad.AddClaim(new Claim(ClaimTypes.Role, user.Rol.ToString()));

                        ClaimsPrincipal principal = new ClaimsPrincipal(identidad);

                        // Ejecutamos el Login
                        await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);

                        if (!string.IsNullOrEmpty(urlIngreso))
                        {
                            return Redirect(urlIngreso);
                        }
                        else
                        {
                            // Redirigimos a la pagina principal
                            return RedirectToAction("Index", "Home");
                        }
                    }
                }
            }

            ViewBag.ErrorEnLogin = "Verifique el usuario y contraseña";
            TempData["UrlIngreso"] = urlIngreso; // Volvemos a enviarla en el TempData para no perderla
            return View();

        }

        [Authorize]
            [HttpPost]
            public async Task<IActionResult> Salir()
            {
                await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);

                return RedirectToAction("Index", "Home");
            }

            [Authorize]
            public IActionResult AccesoDenegado()
            {
                return View();
            }


            public IActionResult Registrarse()
            {
                return View();
            }

            [HttpPost]
            [ValidateAntiForgeryToken]
            public async Task<IActionResult> Registrarse(Usuario usuario, string pass)
            {
                if (ModelState.IsValid)
                {
                    if(!_context.Usuarios.Any(u => u.User == usuario.User))
                    {
                        
                             if (seguridad.ValidarPass(pass))
                             {
                                  usuario.Contraseña = seguridad.EncriptarPass(pass);
                                  usuario.Rol = Rol.UsuarioComun;
                                 _context.Add(usuario);
                                await _context.SaveChangesAsync();
                                return RedirectToAction(nameof(Ingresar));
                             }
                             else
                             {
                                ModelState.AddModelError(nameof(Usuario.Contraseña), "La contraseña no cumple con los requisitos");
                             }
                    }
                    else
                    {
                         ModelState.AddModelError(nameof(Usuario.User), "El usuario ya existe");
                    }
                    
                }
                return View(usuario);
            }
        }
    }

BookStoreProject/Controllers/VentaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BookStoreProject.Context;
using BookStoreProject.Models;
using Microsoft.AspNetCore.Authorization;

namespace BookStoreProject.Controllers
{
    [Authorize]
    public class VentaController : Controller
    {
        private readonly BookStoreDBContext _context;

        public VentaController(BookStoreDBContext context)
        {
            _context = context;
        }
        
        // GET: Venta
        [Authorize(Roles = nameof(Rol.Administrador))]
        public ActionResult Index(string cadenaBuscada)
        {

            var ventas = from v in _context.Ventas.Include(v => v.Libro)
                             select v;

            if (!String.IsNullOrEmpty(cadenaBuscada))
            {
                ventas = ventas.Where(v => v.Libro.Titulo.Contains(cadenaBuscada));
            }

            ViewBag.TotalVentas = ventas.Count();
            ViewBag.TotalVendido = ventas.Select(v => v.Libro.Precio).Sum();
            return View(ventas);
        }

     

        // GET: Venta/Details/5
        [Authorize(Roles = nameof(Rol.Administrador))]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var venta = await _context.Ventas
               .Include(v => v.Libro)
               .FirstOrDefaultAsync(m => m.Id == id);

            if (venta == null)
            {
                return NotFound();
            }

            return View(venta);
        }

        // GET: Venta/Create
        [Authorize(Roles = nameof(Rol.Administrador))]
        public IActionResult Create()
        {
            ViewData["LibroId"] = new SelectList(_context.Libros, "Id", "Autor");
            return View();
        }

        // POST: Venta/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = nameof(Rol.Administrador))]
        public async Task<IActionResult> Create([Bind("Id,Nombre,Apellido,Dni,Calle,Altura,Provincia,Tarjeta,NumeroTarjeta,LibroId")] Venta venta)
        {
            if (ModelState.IsValid)
            {
                _context.Add(venta);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["LibroId"] = new SelectList(_context.Libros, "Id", "Autor", venta.LibroId);
            return View(venta);
        }

        // GET: Venta/Delete/5
        [Authorize(Roles = nameof(Rol.Administrador))]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var venta = await _context.Ventas
                .Include(v => v.Libro)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (venta == null)
            {
                return NotFound();
            }

            return View(venta);
        }

        // POST: Venta/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = nameof(Rol.Administrador))]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var venta = await _context.Ventas.FindAsync(id);
            _context.Ventas.Remove(venta);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = nameof(Rol.Administrador))]
        private bool VentaExists(int id)
        {
            return _context.Ventas.Any(e => e.Id == id);
        }


        public ActionResult Comprar()
        {
            return View();
        }

        
        [HttpPost]
        public ActionResult Comprar(int Id, string Nombre, string Apellido, int Dni, string Calle, int Altura,
            string Provincia, int Telefono, string Email, string Tarjeta, long NumeroTarjeta)
        {
            var venta = new Venta();
            venta.Nombre = Nombre;
            venta.Apellido = Apellido;
            venta.Dni = Dni;
            venta.Calle = Calle;
            venta.Altura = Altura;
            venta.Provincia = Provincia;
            venta.Telefono = Telefono;
            venta.Email = Email;
            venta.Tarjeta = Tarjeta;
            venta.NumeroTarjeta = NumeroTarjeta;
            venta.LibroId = Id;
            var libro = _context.Libros.Find(Id);
            venta.Libro = libro;
            venta.Fecha = DateTime.Now;
            if (ModelState.IsValid)
            {
                _context.Ventas.Add(venta);
            _context.SaveChanges();
                ViewBag.LibroId = venta.LibroId;
                return View("CompraExitosa");

            }
            
            return RedirectToAction("Index", "Home");
        }
        
    }
}

BookStoreProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookStoreProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/css/prueba.css" rel="stylesheet" />
</head>
<body id="bodyLayout">
    <header>
        <nav id="navFunc" class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow">
            <div class="container">
                <a id="logo" class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EmilSinclair</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="func" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="func" asp-area="" asp-controller="Libro" asp-action="Index">Libros</a>
                            </li>
                            <li class="nav-item">
                                <a class="func" asp-area="" asp-controller="Sucursal" asp-action="Index">Sucursales</a>
                            </li>
                            <li class="nav-item">
                                <a class="func" asp-area="" asp-controller="Suscripcion" asp-action="Suscribirse">Suscribirse</a>
                            </li>
                        }


                        @if (User.Identity.IsAuthenticated && User.IsInRole(nameof(Rol.Administrador)))
                        {

                            <li class="nav-item">
                                <a class="func" asp-area="" asp-controller="Suscripcion" asp-action="Index">Suscripciones</a>
                            </li>
                            <li class="nav-item">
                                <a class="func" asp-area="" asp-controller="Venta" asp-action="Index">Ventas</a>
                            </li>
                        }
                    </ul>
                </div>
                @if (User.Identity.IsAuthenticated)
                {
                    <div id="yaIngresado" class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item float-right">
                                <a class="nav-link text-success font-italic" asp-area="">@User.FindFirstValue(ClaimTypes.GivenName)</a>
                            </li>
                            <li class="nav-item float-right">
                                <form asp-controller="Usuario" asp-action="Salir" method="post">
                                    <button type="submit" class="btn btn-danger">Salir</button>
                                </form>
                            </li>
                        </ul>
                    </div> }
                else
                {
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a id="ingresar" class="btn btn-primary" asp-area="" asp-controller="Usuario" asp-action="Ingresar">Ingresar</a>
                            </li>
                        </ul>
                    </div>}
            </div>
        </nav>
    </header>
    <div id="container1" class="container">
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            <div class="redes_conteiner">
                <ul class="redes">
                    <li><a href="https://www.instagram.com/" target="_blank"><img class="red" src="~/imagenes/instagramPic.jpg" alt="Instagram" /></a></li>
                    <li><a href="https://www.facebook.com/" target="_blank"><img class="red" src="~/imagenes/facebookPic.jpg" alt="Facebook" /></a></li>
                    <li><a href="https://www.twitter.com/" target="_blank"><img class="red" src="~/imagenes/twitterPic.jpg" alt="Twitter" /></a></li>
                    <li><p id="copyright"> &copy; 2021 - Libreria EmilSinclair - TODOS LOS DERECHOS RESERVADOS -</p></liid="copyright">
                    <li><a href="https://www.visa.com.ar/tu-visa/encontra-tu-tarjeta/credito.html" target="_blank"><img class="red" src="~/imagenes/visa.jpg" alt="Tarjeta Visa" /></a> </li>
                    <li><a href="https://www.mastercard.com.ar/es-ar.html" target="_blank"><img class="red" src="~/imagenes/mastercard.jpg" alt="Tarjeta Mastercad" /></a></li>
                    <li><a href="https://www.cabal.coop/" target="_blank"><img class="red" src="~/imagenes/cabal.jpg" alt="Tarjeta Cabal" /></a></li>
                    <li><a href="https://www.nativanacion.com.ar/" target="_blank"><img class="red" src="~/imagenes/nativa.jpg" alt="Tarjeta Nativa" /></a></li>
                </ul>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

BookStoreProject/Views/Shared/_Login.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Login</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/fondo-error.css" />
</head>
<body>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>